package com.seecoder.BlueWhale.enums;

public enum CommodityTypeEnum {
    FOOD , CLOTHES, FURNITURE, ELECTRONICS, ENTERTAINMENT, SPORTS, LUXURY;

    public enum CommoditySubTypeEnum {
        VEGETABLES, FRUITS, MEAT, SEAFOOD, SNACKS, DRINKS,  // FOOD

        TOPS, BOTTOMS, DRESSES, OUTERWEAR, SHOES, ACCESSORIES,  // CLOTHES

        BEDS, SOFAS, TABLES, CHAIRS, CABINETS,   // FURNITURE

        PHONES, COMPUTERS, TVS, CAMERAS, HEADPHONES,  // ELECTRONICS

        BOOKS, MOVIES, MUSIC, GAMES,  // ENTERTAINMENT

        FITNESS, YOGA, RUNNING, SWIMMING,   // SPORTS

        JEWELRY, WATCHES, HANDBAGS, OTHERS  // LUXURY
    }


}
